export * from './currencyParser';
export * from './parseToThousands';
export * from './removeWhiteSpaces';
export * from './toOnlyNumbers';
export * from './getTheme';
export * from './ifStyle';
export * from './switchStyle';
export * from './base64';
export * from './pixelToRem';
